config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  devise_for :users#, :except=>["edit","update"]

   root 'welcome#index'
   resources :products
   resources :users, :except=>"new"
get "/upload/grid/*path" => "gridfs#serve"
get "/welcome/search"=> "welcome#search"
get "/products/follow/:id"=>"products#follow", :as=>"product_follow"
get "/users/:id/followlist"=>"users#followlist", :as=>"followlist"
get "/users/:id/productlist"=>"users#productlist", :as=>"productlist"

end

app/models/product.rb
class Product
  include Mongoid::Document
  include Mongoid::Timestamps
  field :name, type: String
  validates_presence_of :name, :message=>"物品名称不能为空"
  validates_length_of :name, :minimum=>2, :maximun=>20,  :too_short=>"标题长度应在2到20字节之间", :too_long=>"标题长度应在2到20字节之间"
   #field :images, type: Array
  field :description, type: String
  validates_presence_of :description, :message=>"商品描述不能为空"
  belongs_to :creater, :class_name=>"User", :inverse_of=>"my_products"
  has_and_belongs_to_many :followers, :class_name=>"User",:autosave=>true, :inverse_of=>"my_follows"
  has_many :product_images
  accepts_nested_attributes_for :product_images, :allow_destroy => true
  has_and_belongs_to_many :tags,:autosave=>true
  accepts_nested_attributes_for :tags, :allow_destroy => true
  validates_presence_of :tags, :message=>"至少得有一个标签"
end

app/models/product_image.rb
class ProductImage
  include Mongoid::Document

#  attr_accessible :image
  mount_uploader :image, ProductUploader
 field :image, type: String
  belongs_to :product
end

app/models/tag.rb
class Tag
  include Mongoid::Document
  field :title, type: String
  has_and_belongs_to_many :products, :autosave=>true
  accepts_nested_attributes_for :products
  index({ :title=>1 }, { unique: true}) 
end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String
  ## User info
  field :name,           type: String, default: ""
  index({ name: 1 }, { unique: true, drop_dups: true })
  field :qqnumber,       type: String, default: ""
  field :telnumber,      type: String, default: ""
  has_many :my_products, :class_name=>"Product", :inverse_of=>"creater"
  has_and_belongs_to_many :my_follows, :class_name=>"Product", :autosave=>true, :inverse_of=>"followers"
 def self.serialize_from_session(key, salt)
    record = to_adapter.get(key[0]["$oid"])
    record if record && record.authenticatable_salt == salt
  end
  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/gridfs_controller.rb
class GridfsController < ApplicationController  
  
  def serve  
    gridfs_path = env["PATH_INFO"].gsub("/upload/grid/", "")  
    begin  
      gridfs_file = Mongoid::GridFS[gridfs_path]  
      self.response_body = gridfs_file.data  
      self.content_type = gridfs_file.content_type  
    rescue  
      self.status = :file_not_found  
      self.content_type = 'text/plain'  
      self.response_body = ''  
    end  
  end  
end  

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :authenticate_user!, :except=>'index'
  def new
     @product=Product.new
   end
   def create
    warn product_params
    product=Product.new(product_params)
    product.creater=current_user
    if product.save
     redirect_to product_path(product.id) 
    else
     flash[:error]=product.errors.values.flatten.join(",")
     redirect_to :back
    end
   end
   def show
   @product=Product.where(:id=>params.permit(:id)[:id]).first
   @images=@product.product_images
   end
   def destroy
   if  Product.destroy_all(:id=>params.permit(:id)[:id])
     flash[:success]="删除成功"
     redirect_to :back
   else
     redirct_to :back
   end
 end
  def follow
    product=Product.where(:id=>params.permit(:id)[:id]).first
    redirect_to :back if !current_user
    if product.followers.include? current_user
       product.followers.delete(current_user)
    else
       product.followers << current_user
    end
    product.save
    redirect_to :back
  end
  private
   def product_params
    params.require(:product).permit(:id,:name,:description, :product_images_attributes=>[:id,:image,:destroy], :tags_attributes=>[:id,:title,:destroy, :product_ids=>[]])
   end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
  end
  def update
   @user=User.where(id: user_params[:id]).first
   @user.name=user_params[:name]
   @user.qqnumber=user_params[:qqnumber]
   @user.telnumber=user_params[:telnumber]
   redirect_to root_path if @user.update
  end
  def followlist
    @products=current_user.my_follows 
  end
  def productlist
    @products=current_user.my_products
  end
 private
   def user_params
    params.require(:user).permit(:id,:email,:name,:qqnumber,:telnumber)
   end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	before_filter :authenticate_user, :except=>['index','search']
	def index
		@products=Product.all
	end
	def userinfo
	end
	def search
		query_str=params.permit(:content)[:content].split(" ").join
		@products=Tag.where(:title=>query_str).map{|tag| tag.products}.flatten
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type.to_sym] || flash_type.to_s
end 
  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade in") do 
              concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
              concat message 
            end)
    end
    nil
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Panzi" %></title>
    <%= csrf_meta_tags %>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
<%= javascript_include_tag :defaults, "nested_form" %>
<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">
 <%= yield(:header) if @content_for_header %>
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
    
<!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

   <style>
      #map-canvas {
        width: 500px;
        height: 400px;
      }
    </style>
    <script src="https://maps.googleapis.com/maps/api/js"></script>
    <script>
      function initialize() {
        var mapCanvas = document.getElementById('map-canvas');
        var mapOptions = {
          center: new google.maps.LatLng(44.5403, -78.5463),
          zoom: 8,
          mapTypeId: google.maps.MapTypeId.ROADMAP
        }
        var map = new google.maps.Map(mapCanvas, mapOptions)
      }
      google.maps.event.addDomListener(window, 'load', initialize);
    </script>
 <%= javascript_include_tag "application" %>
  </head>
  <body>

<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">

    <!-- スマートフォンサイズで表示されるメニューボタンとテキスト -->
    <div class="navbar-header">

      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#nav-menu-3">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      
      <!-- タイトルなどのテキスト -->
      <a class="navbar-brand" href="/">接盘子</a>

    </div>

    <!-- グローバルナビの中身 -->
    <div class="collapse navbar-collapse" id="nav-menu-3">
      <!-- 各ナビゲーションメニュー -->
      <ul class="nav navbar-nav pull-right">
        <!-- ドロップダウンのメニューも配置可能 -->
       <%if current_user%>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%=current_user.email%> <b class="caret"></b></a>
          <ul class="dropdown-menu pull-right">
            <li><%=link_to "修改个人信息", edit_user_path(current_user.id)%></li>
            <li><%=link_to "注销登陆", destroy_user_session_path, :method => :delete%></li>
            </ul>
        </li>
        <%else%>
            <li><%=link_to "登陆", new_user_session_path%></li>
            <li><%=link_to "注册", new_user_registration_path%></li>
        <%end%>
     </ul>
     <form class="navbar-form navbar-right" role="search" action="/welcome/search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search", name="content">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>

    </div>
  </div>
</nav>
    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= flash_messages %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3><%= link_to "发布", new_product_path, :class=>"btn btn-primary"%></h3>
            <ul class="nav nav-list">
              <li><%= link_to "关注中", followlist_path(current_user.id) if current_user %></li>
              <li><%= link_to "我发布的", productlist_path(current_user.id) if current_user  %></li>
            </ul>
            <h3>热门标签</h3>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2015</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/layouts/index_layout.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Panzi" %></title>
    <%= csrf_meta_tags %>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
<%= javascript_include_tag :defaults, "nested_form" %>
<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
    
<!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

   <style>
      #map-canvas {
        width: 500px;
        height: 400px;
      }
    </style>
    <script src="https://maps.googleapis.com/maps/api/js"></script>
    <script>
      function initialize() {
        var mapCanvas = document.getElementById('map-canvas');
        var mapOptions = {
          center: new google.maps.LatLng(44.5403, -78.5463),
          zoom: 8,
          mapTypeId: google.maps.MapTypeId.ROADMAP
        }
        var map = new google.maps.Map(mapCanvas, mapOptions)
      }
      google.maps.event.addDomListener(window, 'load', initialize);
    </script>
 <%= javascript_include_tag "application" %>
  </head>
  <body>

<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">

    <!-- スマートフォンサイズで表示されるメニューボタンとテキスト -->
    <div class="navbar-header">

      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#nav-menu-3">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      
      <!-- タイトルなどのテキスト -->
      <a class="navbar-brand" href="/">接盘子</a>

    </div>

    <!-- グローバルナビの中身 -->
    <div class="collapse navbar-collapse" id="nav-menu-3">
      <!-- 各ナビゲーションメニュー -->
      <ul class="nav navbar-nav pull-right">
        <!-- ドロップダウンのメニューも配置可能 -->
       <%if current_user%>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%=current_user.email%> <b class="caret"></b></a>
          <ul class="dropdown-menu pull-right">
            <li><%=link_to "修改个人信息", edit_user_path(current_user.id)%></li>
            <li><%=link_to "注销登陆", destroy_user_session_path, :method => :delete%></li>
            </ul>
        </li>
        <%else%>
            <li><%=link_to "登陆", new_user_session_path%></li>
            <li><%=link_to "注册", new_user_registration_path%></li>
        <%end%>
     </ul>
     <form class="navbar-form navbar-right" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>

    </div>
  </div>
</nav>
    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3><%= link_to "发布", new_product_path, :class=>"btn btn-primary"%></h3>
            <ul class="nav nav-list">
              <li><%= link_to "关注中", "#"  %></li>
              <li><%= link_to "我发布的", "#"  %></li>
            </ul>
            <h3>热门标签</h3>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2015</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/products/new.html.erb
<div class="col-md-6">
<h3>发布</h3>
<%=nested_form_for @product do |f|%>
    <div class="form-group">
       <%= f.label "名称:", class: "col-md-4 control-label" %>
       <%=f.text_field :name, :class=>"form-control"%>
    </div>
     <div>
      <%= f.fields_for :product_images do |fi| %>
        <% if fi.object.new_record? %>
            <%= fi.file_field :image %>
        <% else %>
            <%= image_tag fi.object.image.url %>
            <%= fi.link_to_remove "Remove" %>
        <% end %>
      <% end %>
      <%= f.link_to_add "+添加图像", :product_images, :class=>"btn btn-mini" %>
    </div>
    <div class="form-group">
       <%= f.label "描述:", class: "col-md-4 control-label" %>
       <%=f.text_area :description, :class=>"form-control ", :rows=>"5"%>
    </div>
    <div>
      <%= f.fields_for :tags do |tag| %>
            <%= tag.text_field :title %>
      <% end %>
      <%= f.link_to_add "+添加标签", :tags, :class=>"btn btn-mini" %>
    </div>

<%=f.submit "提交", :class=>"btn btn-primary"%>
<%end%>
</div>
<!--<form>
    <div class="form-group">
        <label for="inputEmail">Email</label>
        <input type="email" class="form-control" id="inputEmail" placeholder="Email">
    </div>
    <div class="form-group">
        <label for="inputPassword">Password</label>
        <input type="password" class="form-control" id="inputPassword" placeholder="Password">
    </div>
    <div class="checkbox">
        <label><input type="checkbox"> Remember me</label>
    </div>
    <button type="submit" class="btn btn-primary">Login</button>
</form>-->

app/views/products/show.html.erb
<div class="col-md-6">
<h3><%=@product.name%></h3>
<%=@product.description%>
<%=@product.creater.name%>
<%@product.product_images.each do |image|%>
<%=image_tag image.image.thumb%>
<%end%>
</div>

app/views/users/edit.html.erb
<div class="col-md-6">
<%=form_for current_user, :html=>{:class=>"form-group"}  do |f|%>
    <div class="form-group">
       <%= f.label "邮件(E-mail):", class: "col-md-4 control-label" %>
       <%=f.email_field :email, :class=>"form-control ", :disabled=>"disabled"%>
    </div>
       <%=f.hidden_field :id%>
    <div class="form-group">
       <%= f.label "昵称:", class: "col-md-4 control-label" %>
       <%=f.text_field :name, :class=>"form-control "%>
    </div>
 <div class="form-group">
       <%= f.label :qq, "QQ号码:", class: "col-md-4 control-label" %>
       <%=f.text_field :qqnumber, :class=>"form-control "%>
    </div>
 <div class="form-group">
       <%= f.label "联系电话:", class: "col-md-4 control-label" %>
       <%=f.text_field :telnumber, :class=>"form-control "%>
    </div>

<%=f.submit "提交", :class=>"btn btn-primary"%>
<%end%>
</div>
<!--<form>
    <div class="form-group">
        <label for="inputEmail">Email</label>
        <input type="email" class="form-control" id="inputEmail" placeholder="Email">
    </div>
    <div class="form-group">
        <label for="inputPassword">Password</label>
        <input type="password" class="form-control" id="inputPassword" placeholder="Password">
    </div>
    <div class="checkbox">
        <label><input type="checkbox"> Remember me</label>
    </div>
    <button type="submit" class="btn btn-primary">Login</button>
</form>-->

app/views/users/followlist.html.erb
<!--<div id="map-canvas">
</div>
-->
<% content_for :header do -%>
  <%= stylesheet_link_tag 'box' %>
<% end -%>
<div class="row">
<%@products.each do |product|%>
<div class="panel panel-success col-md-4 col-md-offset-1">
<center>
<span style="font-size: 14pt;"><%=link_to product.name, product_path(product.id)%></span>
</center>
<div class="pull-right">
<%if current_user and product.followers.include? current_user%>
<%=link_to "-取消关注", product_follow_path(product.id)%>
<%else%>
<%=link_to "+关注", product_follow_path(product.id)%>
<%end%>
</div>
<div class="panel-body">
<span style="font-size :12pt;"><%=product.description%></span>
<div class="thumb">
<%product.product_images.each do |image|%>
<%=link_to image_tag(image.image.thumb), image.image.url, :"data-lightbox"=>image.id%>
<%end%>
<h6>标签:</h6>
<%product.tags.each do |tag|%>
<%=tag.title%>
<%end%>
<%=link_to "delete", product_path(product.id), :method=>"delete", :class=>"btn btn-danger pull-right" if current_user==product.creater%>
</div>
</div>
</div>
<%end%>
</div>

app/views/users/productlist.html.erb
<!--<div id="map-canvas">
</div>
-->
<% content_for :header do -%>
  <%= stylesheet_link_tag 'box' %>
<% end -%>
<div class="row">
<%@products.each do |product|%>
<div class="panel panel-success col-md-4 col-md-offset-1">
<center>
<span style="font-size: 14pt;"><%=link_to product.name, product_path(product.id)%></span>
</center>
<div class="pull-right">
<%if current_user and product.followers.include? current_user%>
<%=link_to "-取消关注", product_follow_path(product.id)%>
<%else%>
<%=link_to "+关注", product_follow_path(product.id)%>
<%end%>
</div>
<div class="panel-body">
<span style="font-size :12pt;"><%=product.description%></span>
<div class="thumb">
<%product.product_images.each do |image|%>
<%=link_to image_tag(image.image.thumb), image.image.url, :"data-lightbox"=>image.id%>
<%end%>
<h6>标签:</h6>
<%product.tags.each do |tag|%>
<%=tag.title%>
<%end%>
<%=link_to "delete", product_path(product.id), :method=>"delete", :class=>"btn btn-danger pull-right" if current_user==product.creater%>
</div>
</div>
</div>
<%end%>
</div>

app/views/welcome/index.html.erb
<!--<div id="map-canvas">
</div>
-->
<% content_for :header do -%>
	<%= stylesheet_link_tag 'box' %>
<% end -%>
<div class="row">
	<%@products.each do |product|%>
		<div class="panel panel-success col-md-4 col-md-offset-1">
			<center>
				<span style="font-size: 14pt;"><%=link_to product.name, product_path(product.id)%></span>
			</center>
			<div class="pull-right">
				<%if current_user and product.followers.include? current_user%>
					<%=link_to "-取消关注", product_follow_path(product.id)%>
				<%else%>
					<%=link_to "+关注", product_follow_path(product.id)%>
				<%end%>
			</div>
			<div class="panel-body">
				<span style="font-size :12pt;"><%=product.description%></span>
				<div class="thumb">
					<%product.product_images.each do |image|%>
						<%=link_to image_tag(image.image.thumb), image.image.url, :"data-lightbox"=>image.id%>
					<%end%>
					<h6>标签:</h6>
					<%product.tags.each do |tag|%>
						<%=tag.title%>
					<%end%>
					<h6>联系:</h6>
					<%=product.creater.email%>
					<p><%="QQ: "+product.creater.qqnumber if product.creater.qqnumber!=""%></p>
					<%="TEL: "+product.creater.telnumber if product.creater.telnumber!=""%>
					<%=link_to "delete", product_path(product.id), :method=>"delete", :class=>"btn btn-danger pull-right" if current_user==product.creater%>
				</div>
			</div>
		</div>
	<%end%>
</div>

app/views/welcome/search.html.erb
<!--<div id="map-canvas">
</div>
-->
<% content_for :header do -%>
  <%= stylesheet_link_tag 'box' %>
<% end -%>
<center>
<h3><%='找到关于"'+params[:content]+'"的'+"#{@products.size}项结果"%></h3>
</center>
<div class="row">
<%@products.each do |product|%>
<div class="panel panel-success col-md-4 col-md-offset-1">
<center>
<span style="font-size: 14pt;"><%=link_to product.name, product_path(product.id)%></span>
</center>
<div class="panel-body">
<span style="font-size :12pt;"><%=product.description%></span>
<div class="thumb">
<%product.product_images.each do |image|%>
<%=link_to image_tag(image.image.thumb), image.image.url, :"data-lightbox"=>image.id%>
<%end%>
<h6>标签:</h6>
<%product.tags.each do |tag|%>
<%=tag.title%>
<%end%>
<%=link_to "delete", product_path(product.id), :method=>"delete", :class=>"btn btn-danger pull-right" if current_user==product.creater%>
</div>
</div>
</div>
<%end%>
</div>

app/views/welcome/usrinfo.html.erb
<% form_for @user do |f|%>
<%=f.label "please enter a user name"%>
<%=f.text_field  :name%>
<%=f.submit%>